// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/core/services/search/bm25_index_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/core/services/search/bm25_search_service.dart' as _i2;
import 'package:app/core/services/search/models/bm25_search_result.dart' as _i5;
import 'package:app/features/recorder/models/recording.dart' as _i4;
import 'package:app/features/recorder/services/storage_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BM25SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBM25SearchService extends _i1.Mock implements _i2.BM25SearchService {
  MockBM25SearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get needsRebuild =>
      (super.noSuchMethod(Invocation.getter(#needsRebuild), returnValue: false)
          as bool);

  @override
  int get indexSize =>
      (super.noSuchMethod(Invocation.getter(#indexSize), returnValue: 0)
          as int);

  @override
  _i3.Future<void> buildIndex(List<_i4.Recording>? recordings) =>
      (super.noSuchMethod(
            Invocation.method(#buildIndex, [recordings]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.BM25SearchResult>> search(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query], {#limit: limit}),
            returnValue: _i3.Future<List<_i5.BM25SearchResult>>.value(
              <_i5.BM25SearchResult>[],
            ),
          )
          as _i3.Future<List<_i5.BM25SearchResult>>);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i6.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i3.Future<void> ensureInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureInitialized, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void forceRefresh() => super.noSuchMethod(
    Invocation.method(#forceRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> startWatchingFilesystem({void Function()? onChange}) =>
      (super.noSuchMethod(
            Invocation.method(#startWatchingFilesystem, [], {
              #onChange: onChange,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopWatchingFilesystem() =>
      (super.noSuchMethod(
            Invocation.method(#stopWatchingFilesystem, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void setIgnoredRecordingPath(String? path) => super.noSuchMethod(
    Invocation.method(#setIgnoredRecordingPath, [path]),
    returnValueForMissingStub: null,
  );

  @override
  void clearIgnoredRecordingPath() => super.noSuchMethod(
    Invocation.method(#clearIgnoredRecordingPath, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> getSyncFolderPath() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncFolderPath, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getSyncFolderPath, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> setSyncFolderPath(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setSyncFolderPath, [path]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.Recording>> getRecordings({
    bool? includeOrphaned = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordings, [], {
              #includeOrphaned: includeOrphaned,
            }),
            returnValue: _i3.Future<List<_i4.Recording>>.value(
              <_i4.Recording>[],
            ),
          )
          as _i3.Future<List<_i4.Recording>>);

  @override
  _i3.Future<String?> saveRecording(_i4.Recording? recording) =>
      (super.noSuchMethod(
            Invocation.method(#saveRecording, [recording]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> updateRecording(_i4.Recording? updatedRecording) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecording, [updatedRecording]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> appendToRecording({
    required String? recordingId,
    required String? newTranscript,
    required double? newSegmentEndSeconds,
    required DateTime? segmentRecordedAt,
    required double? newFileSizeKB,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#appendToRecording, [], {
              #recordingId: recordingId,
              #newTranscript: newTranscript,
              #newSegmentEndSeconds: newSegmentEndSeconds,
              #segmentRecordedAt: segmentRecordedAt,
              #newFileSizeKB: newFileSizeKB,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteRecording(String? recordingId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecording, [recordingId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Recording?> getRecording(String? recordingId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecording, [recordingId]),
            returnValue: _i3.Future<_i4.Recording?>.value(),
          )
          as _i3.Future<_i4.Recording?>);

  @override
  _i3.Future<void> clearAllRecordings() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllRecordings, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getOpenAIApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#getOpenAIApiKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> saveOpenAIApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#saveOpenAIApiKey, [apiKey]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteOpenAIApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#deleteOpenAIApiKey, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasOpenAIApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#hasOpenAIApiKey, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getGeminiApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#getGeminiApiKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> saveGeminiApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#saveGeminiApiKey, [apiKey]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteGeminiApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#deleteGeminiApiKey, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasGeminiApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#hasGeminiApiKey, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String> getTranscriptionMode() =>
      (super.noSuchMethod(
            Invocation.method(#getTranscriptionMode, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getTranscriptionMode, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> setTranscriptionMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setTranscriptionMode, [mode]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getPreferredWhisperModel() =>
      (super.noSuchMethod(
            Invocation.method(#getPreferredWhisperModel, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> setPreferredWhisperModel(String? modelName) =>
      (super.noSuchMethod(
            Invocation.method(#setPreferredWhisperModel, [modelName]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> getAutoTranscribe() =>
      (super.noSuchMethod(
            Invocation.method(#getAutoTranscribe, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setAutoTranscribe(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoTranscribe, [enabled]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> getAutoPauseRecording() =>
      (super.noSuchMethod(
            Invocation.method(#getAutoPauseRecording, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setAutoPauseRecording(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoPauseRecording, [enabled]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> getAudioDebugOverlay() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioDebugOverlay, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setAudioDebugOverlay(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAudioDebugOverlay, [enabled]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String> getTitleGenerationMode() =>
      (super.noSuchMethod(
            Invocation.method(#getTitleGenerationMode, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getTitleGenerationMode, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> setTitleGenerationMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setTitleGenerationMode, [mode]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getPreferredGemmaModel() =>
      (super.noSuchMethod(
            Invocation.method(#getPreferredGemmaModel, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> setPreferredGemmaModel(String? modelName) =>
      (super.noSuchMethod(
            Invocation.method(#setPreferredGemmaModel, [modelName]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getOllamaModel() =>
      (super.noSuchMethod(
            Invocation.method(#getOllamaModel, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> setOllamaModel(String? modelName) =>
      (super.noSuchMethod(
            Invocation.method(#setOllamaModel, [modelName]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getPreferredSmolLMModel() =>
      (super.noSuchMethod(
            Invocation.method(#getPreferredSmolLMModel, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> setPreferredSmolLMModel(String? modelName) =>
      (super.noSuchMethod(
            Invocation.method(#setPreferredSmolLMModel, [modelName]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getHuggingFaceToken() =>
      (super.noSuchMethod(
            Invocation.method(#getHuggingFaceToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> saveHuggingFaceToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveHuggingFaceToken, [token]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteHuggingFaceToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteHuggingFaceToken, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasHuggingFaceToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasHuggingFaceToken, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getGitHubToken() =>
      (super.noSuchMethod(
            Invocation.method(#getGitHubToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> saveGitHubToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveGitHubToken, [token]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteGitHubToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteGitHubToken, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasGitHubToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasGitHubToken, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getGitHubRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getGitHubRefreshToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> saveGitHubRefreshToken(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#saveGitHubRefreshToken, [refreshToken]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<DateTime?> getGitHubTokenExpiresAt() =>
      (super.noSuchMethod(
            Invocation.method(#getGitHubTokenExpiresAt, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<bool> saveGitHubTokenExpiresAt(DateTime? expiresAt) =>
      (super.noSuchMethod(
            Invocation.method(#saveGitHubTokenExpiresAt, [expiresAt]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<DateTime?> getGitHubRefreshTokenExpiresAt() =>
      (super.noSuchMethod(
            Invocation.method(#getGitHubRefreshTokenExpiresAt, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<bool> saveGitHubRefreshTokenExpiresAt(DateTime? expiresAt) =>
      (super.noSuchMethod(
            Invocation.method(#saveGitHubRefreshTokenExpiresAt, [expiresAt]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getGitHubRepositoryUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getGitHubRepositoryUrl, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> saveGitHubRepositoryUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#saveGitHubRepositoryUrl, [url]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteGitHubRepositoryUrl() =>
      (super.noSuchMethod(
            Invocation.method(#deleteGitHubRepositoryUrl, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isGitSyncEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isGitSyncEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> setGitSyncEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setGitSyncEnabled, [enabled]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
